<?php
/**
 * StreamingEventRow
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  DocuSign\Monitor
 * @author   Swagger Codegen team <apihelp@docusign.com>
 * @license  The Docusign PHP Client SDK is licensed under the MIT License.
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Monitor API
 *
 * An API for an integrator to access the features of Docusign Monitor
 *
 * OpenAPI spec version: v3.0
 * Contact: devcenter@docusign.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.21
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace DocuSign\Monitor\Model;

use \ArrayAccess;
use DocuSign\Monitor\ObjectSerializer;

/**
 * StreamingEventRow Class Doc Comment
 *
 * @category    Class
 * @package     DocuSign\Monitor
 * @author      Swagger Codegen team <apihelp@docusign.com>
 * @license     The Docusign PHP Client SDK is licensed under the MIT License.
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class StreamingEventRow implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'StreamingEventRow';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'timestamp' => '\DateTime',
        'event_id' => '?string',
        'site' => '?string',
        'account_id' => '?string',
        'organization_id' => '?string',
        'user_id' => '?string',
        'integrator_key' => '?string',
        'user_agent' => '?string',
        'user_agent_client_info' => '\DocuSign\Monitor\Model\UserAgentClientInfo',
        'ip_address' => '?string',
        'ip_address_location' => '\DocuSign\Monitor\Model\IpAddressLocation',
        'object' => '?string',
        'action' => '?string',
        'property' => '?string',
        'field' => '?string',
        'result' => '?string',
        'source' => '?string',
        'is_user_member_of_domain' => '?bool',
        'referenced_user_is_member_of_domain' => '?bool',
        'referenced_user_id' => '?string',
        'proxy_status' => '?string',
        'proxy_type' => '?string',
        'proxy_level' => '?string',
        'latitude' => 'double',
        'longitude' => 'double',
        'city' => '?string',
        'state' => '?string',
        'country' => '?string',
        'device' => '?string',
        'browser' => '?string',
        'os' => '?string',
        'affected_user_id' => '?string',
        'affected_user_is_member_of_domain' => '?bool',
        'data' => 'map[string,object]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'timestamp' => 'date-time',
        'event_id' => null,
        'site' => null,
        'account_id' => null,
        'organization_id' => null,
        'user_id' => null,
        'integrator_key' => null,
        'user_agent' => null,
        'user_agent_client_info' => null,
        'ip_address' => null,
        'ip_address_location' => null,
        'object' => null,
        'action' => null,
        'property' => null,
        'field' => null,
        'result' => null,
        'source' => null,
        'is_user_member_of_domain' => null,
        'referenced_user_is_member_of_domain' => null,
        'referenced_user_id' => null,
        'proxy_status' => null,
        'proxy_type' => null,
        'proxy_level' => null,
        'latitude' => 'double',
        'longitude' => 'double',
        'city' => null,
        'state' => null,
        'country' => null,
        'device' => null,
        'browser' => null,
        'os' => null,
        'affected_user_id' => null,
        'affected_user_is_member_of_domain' => null,
        'data' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'timestamp' => 'timestamp',
        'event_id' => 'eventId',
        'site' => 'site',
        'account_id' => 'accountId',
        'organization_id' => 'organizationId',
        'user_id' => 'userId',
        'integrator_key' => 'integratorKey',
        'user_agent' => 'userAgent',
        'user_agent_client_info' => 'userAgentClientInfo',
        'ip_address' => 'ipAddress',
        'ip_address_location' => 'ipAddressLocation',
        'object' => 'object',
        'action' => 'action',
        'property' => 'property',
        'field' => 'field',
        'result' => 'result',
        'source' => 'source',
        'is_user_member_of_domain' => 'isUserMemberOfDomain',
        'referenced_user_is_member_of_domain' => 'referencedUserIsMemberOfDomain',
        'referenced_user_id' => 'referencedUserId',
        'proxy_status' => 'proxyStatus',
        'proxy_type' => 'proxyType',
        'proxy_level' => 'proxyLevel',
        'latitude' => 'latitude',
        'longitude' => 'longitude',
        'city' => 'city',
        'state' => 'state',
        'country' => 'country',
        'device' => 'device',
        'browser' => 'browser',
        'os' => 'os',
        'affected_user_id' => 'affectedUserId',
        'affected_user_is_member_of_domain' => 'affectedUserIsMemberOfDomain',
        'data' => 'data'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'timestamp' => 'setTimestamp',
        'event_id' => 'setEventId',
        'site' => 'setSite',
        'account_id' => 'setAccountId',
        'organization_id' => 'setOrganizationId',
        'user_id' => 'setUserId',
        'integrator_key' => 'setIntegratorKey',
        'user_agent' => 'setUserAgent',
        'user_agent_client_info' => 'setUserAgentClientInfo',
        'ip_address' => 'setIpAddress',
        'ip_address_location' => 'setIpAddressLocation',
        'object' => 'setObject',
        'action' => 'setAction',
        'property' => 'setProperty',
        'field' => 'setField',
        'result' => 'setResult',
        'source' => 'setSource',
        'is_user_member_of_domain' => 'setIsUserMemberOfDomain',
        'referenced_user_is_member_of_domain' => 'setReferencedUserIsMemberOfDomain',
        'referenced_user_id' => 'setReferencedUserId',
        'proxy_status' => 'setProxyStatus',
        'proxy_type' => 'setProxyType',
        'proxy_level' => 'setProxyLevel',
        'latitude' => 'setLatitude',
        'longitude' => 'setLongitude',
        'city' => 'setCity',
        'state' => 'setState',
        'country' => 'setCountry',
        'device' => 'setDevice',
        'browser' => 'setBrowser',
        'os' => 'setOs',
        'affected_user_id' => 'setAffectedUserId',
        'affected_user_is_member_of_domain' => 'setAffectedUserIsMemberOfDomain',
        'data' => 'setData'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'timestamp' => 'getTimestamp',
        'event_id' => 'getEventId',
        'site' => 'getSite',
        'account_id' => 'getAccountId',
        'organization_id' => 'getOrganizationId',
        'user_id' => 'getUserId',
        'integrator_key' => 'getIntegratorKey',
        'user_agent' => 'getUserAgent',
        'user_agent_client_info' => 'getUserAgentClientInfo',
        'ip_address' => 'getIpAddress',
        'ip_address_location' => 'getIpAddressLocation',
        'object' => 'getObject',
        'action' => 'getAction',
        'property' => 'getProperty',
        'field' => 'getField',
        'result' => 'getResult',
        'source' => 'getSource',
        'is_user_member_of_domain' => 'getIsUserMemberOfDomain',
        'referenced_user_is_member_of_domain' => 'getReferencedUserIsMemberOfDomain',
        'referenced_user_id' => 'getReferencedUserId',
        'proxy_status' => 'getProxyStatus',
        'proxy_type' => 'getProxyType',
        'proxy_level' => 'getProxyLevel',
        'latitude' => 'getLatitude',
        'longitude' => 'getLongitude',
        'city' => 'getCity',
        'state' => 'getState',
        'country' => 'getCountry',
        'device' => 'getDevice',
        'browser' => 'getBrowser',
        'os' => 'getOs',
        'affected_user_id' => 'getAffectedUserId',
        'affected_user_is_member_of_domain' => 'getAffectedUserIsMemberOfDomain',
        'data' => 'getData'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->container['timestamp'] = isset($data['timestamp']) ? $data['timestamp'] : null;
        $this->container['event_id'] = isset($data['event_id']) ? $data['event_id'] : null;
        $this->container['site'] = isset($data['site']) ? $data['site'] : null;
        $this->container['account_id'] = isset($data['account_id']) ? $data['account_id'] : null;
        $this->container['organization_id'] = isset($data['organization_id']) ? $data['organization_id'] : null;
        $this->container['user_id'] = isset($data['user_id']) ? $data['user_id'] : null;
        $this->container['integrator_key'] = isset($data['integrator_key']) ? $data['integrator_key'] : null;
        $this->container['user_agent'] = isset($data['user_agent']) ? $data['user_agent'] : null;
        $this->container['user_agent_client_info'] = isset($data['user_agent_client_info']) ? $data['user_agent_client_info'] : null;
        $this->container['ip_address'] = isset($data['ip_address']) ? $data['ip_address'] : null;
        $this->container['ip_address_location'] = isset($data['ip_address_location']) ? $data['ip_address_location'] : null;
        $this->container['object'] = isset($data['object']) ? $data['object'] : null;
        $this->container['action'] = isset($data['action']) ? $data['action'] : null;
        $this->container['property'] = isset($data['property']) ? $data['property'] : null;
        $this->container['field'] = isset($data['field']) ? $data['field'] : null;
        $this->container['result'] = isset($data['result']) ? $data['result'] : null;
        $this->container['source'] = isset($data['source']) ? $data['source'] : null;
        $this->container['is_user_member_of_domain'] = isset($data['is_user_member_of_domain']) ? $data['is_user_member_of_domain'] : null;
        $this->container['referenced_user_is_member_of_domain'] = isset($data['referenced_user_is_member_of_domain']) ? $data['referenced_user_is_member_of_domain'] : null;
        $this->container['referenced_user_id'] = isset($data['referenced_user_id']) ? $data['referenced_user_id'] : null;
        $this->container['proxy_status'] = isset($data['proxy_status']) ? $data['proxy_status'] : null;
        $this->container['proxy_type'] = isset($data['proxy_type']) ? $data['proxy_type'] : null;
        $this->container['proxy_level'] = isset($data['proxy_level']) ? $data['proxy_level'] : null;
        $this->container['latitude'] = isset($data['latitude']) ? $data['latitude'] : null;
        $this->container['longitude'] = isset($data['longitude']) ? $data['longitude'] : null;
        $this->container['city'] = isset($data['city']) ? $data['city'] : null;
        $this->container['state'] = isset($data['state']) ? $data['state'] : null;
        $this->container['country'] = isset($data['country']) ? $data['country'] : null;
        $this->container['device'] = isset($data['device']) ? $data['device'] : null;
        $this->container['browser'] = isset($data['browser']) ? $data['browser'] : null;
        $this->container['os'] = isset($data['os']) ? $data['os'] : null;
        $this->container['affected_user_id'] = isset($data['affected_user_id']) ? $data['affected_user_id'] : null;
        $this->container['affected_user_is_member_of_domain'] = isset($data['affected_user_is_member_of_domain']) ? $data['affected_user_is_member_of_domain'] : null;
        $this->container['data'] = isset($data['data']) ? $data['data'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets timestamp
     *
     * @return \DateTime
     */
    public function getTimestamp()
    {
        return $this->container['timestamp'];
    }

    /**
     * Sets timestamp
     *
     * @param \DateTime $timestamp timestamp
     *
     * @return $this
     */
    public function setTimestamp($timestamp)
    {
        $this->container['timestamp'] = $timestamp;

        return $this;
    }

    /**
     * Gets event_id
     *
     * @return ?string
     */
    public function getEventId()
    {
        return $this->container['event_id'];
    }

    /**
     * Sets event_id
     *
     * @param ?string $event_id event_id
     *
     * @return $this
     */
    public function setEventId($event_id)
    {
        $this->container['event_id'] = $event_id;

        return $this;
    }

    /**
     * Gets site
     *
     * @return ?string
     */
    public function getSite()
    {
        return $this->container['site'];
    }

    /**
     * Sets site
     *
     * @param ?string $site site
     *
     * @return $this
     */
    public function setSite($site)
    {
        $this->container['site'] = $site;

        return $this;
    }

    /**
     * Gets account_id
     *
     * @return ?string
     */
    public function getAccountId()
    {
        return $this->container['account_id'];
    }

    /**
     * Sets account_id
     *
     * @param ?string $account_id account_id
     *
     * @return $this
     */
    public function setAccountId($account_id)
    {
        $this->container['account_id'] = $account_id;

        return $this;
    }

    /**
     * Gets organization_id
     *
     * @return ?string
     */
    public function getOrganizationId()
    {
        return $this->container['organization_id'];
    }

    /**
     * Sets organization_id
     *
     * @param ?string $organization_id organization_id
     *
     * @return $this
     */
    public function setOrganizationId($organization_id)
    {
        $this->container['organization_id'] = $organization_id;

        return $this;
    }

    /**
     * Gets user_id
     *
     * @return ?string
     */
    public function getUserId()
    {
        return $this->container['user_id'];
    }

    /**
     * Sets user_id
     *
     * @param ?string $user_id user_id
     *
     * @return $this
     */
    public function setUserId($user_id)
    {
        $this->container['user_id'] = $user_id;

        return $this;
    }

    /**
     * Gets integrator_key
     *
     * @return ?string
     */
    public function getIntegratorKey()
    {
        return $this->container['integrator_key'];
    }

    /**
     * Sets integrator_key
     *
     * @param ?string $integrator_key integrator_key
     *
     * @return $this
     */
    public function setIntegratorKey($integrator_key)
    {
        $this->container['integrator_key'] = $integrator_key;

        return $this;
    }

    /**
     * Gets user_agent
     *
     * @return ?string
     */
    public function getUserAgent()
    {
        return $this->container['user_agent'];
    }

    /**
     * Sets user_agent
     *
     * @param ?string $user_agent user_agent
     *
     * @return $this
     */
    public function setUserAgent($user_agent)
    {
        $this->container['user_agent'] = $user_agent;

        return $this;
    }

    /**
     * Gets user_agent_client_info
     *
     * @return \DocuSign\Monitor\Model\UserAgentClientInfo
     */
    public function getUserAgentClientInfo()
    {
        return $this->container['user_agent_client_info'];
    }

    /**
     * Sets user_agent_client_info
     *
     * @param \DocuSign\Monitor\Model\UserAgentClientInfo $user_agent_client_info user_agent_client_info
     *
     * @return $this
     */
    public function setUserAgentClientInfo($user_agent_client_info)
    {
        $this->container['user_agent_client_info'] = $user_agent_client_info;

        return $this;
    }

    /**
     * Gets ip_address
     *
     * @return ?string
     */
    public function getIpAddress()
    {
        return $this->container['ip_address'];
    }

    /**
     * Sets ip_address
     *
     * @param ?string $ip_address ip_address
     *
     * @return $this
     */
    public function setIpAddress($ip_address)
    {
        $this->container['ip_address'] = $ip_address;

        return $this;
    }

    /**
     * Gets ip_address_location
     *
     * @return \DocuSign\Monitor\Model\IpAddressLocation
     */
    public function getIpAddressLocation()
    {
        return $this->container['ip_address_location'];
    }

    /**
     * Sets ip_address_location
     *
     * @param \DocuSign\Monitor\Model\IpAddressLocation $ip_address_location ip_address_location
     *
     * @return $this
     */
    public function setIpAddressLocation($ip_address_location)
    {
        $this->container['ip_address_location'] = $ip_address_location;

        return $this;
    }

    /**
     * Gets object
     *
     * @return ?string
     */
    public function getObject()
    {
        return $this->container['object'];
    }

    /**
     * Sets object
     *
     * @param ?string $object object
     *
     * @return $this
     */
    public function setObject($object)
    {
        $this->container['object'] = $object;

        return $this;
    }

    /**
     * Gets action
     *
     * @return ?string
     */
    public function getAction()
    {
        return $this->container['action'];
    }

    /**
     * Sets action
     *
     * @param ?string $action action
     *
     * @return $this
     */
    public function setAction($action)
    {
        $this->container['action'] = $action;

        return $this;
    }

    /**
     * Gets property
     *
     * @return ?string
     */
    public function getProperty()
    {
        return $this->container['property'];
    }

    /**
     * Sets property
     *
     * @param ?string $property property
     *
     * @return $this
     */
    public function setProperty($property)
    {
        $this->container['property'] = $property;

        return $this;
    }

    /**
     * Gets field
     *
     * @return ?string
     */
    public function getField()
    {
        return $this->container['field'];
    }

    /**
     * Sets field
     *
     * @param ?string $field field
     *
     * @return $this
     */
    public function setField($field)
    {
        $this->container['field'] = $field;

        return $this;
    }

    /**
     * Gets result
     *
     * @return ?string
     */
    public function getResult()
    {
        return $this->container['result'];
    }

    /**
     * Sets result
     *
     * @param ?string $result result
     *
     * @return $this
     */
    public function setResult($result)
    {
        $this->container['result'] = $result;

        return $this;
    }

    /**
     * Gets source
     *
     * @return ?string
     */
    public function getSource()
    {
        return $this->container['source'];
    }

    /**
     * Sets source
     *
     * @param ?string $source source
     *
     * @return $this
     */
    public function setSource($source)
    {
        $this->container['source'] = $source;

        return $this;
    }

    /**
     * Gets is_user_member_of_domain
     *
     * @return ?bool
     */
    public function getIsUserMemberOfDomain()
    {
        return $this->container['is_user_member_of_domain'];
    }

    /**
     * Sets is_user_member_of_domain
     *
     * @param ?bool $is_user_member_of_domain is_user_member_of_domain
     *
     * @return $this
     */
    public function setIsUserMemberOfDomain($is_user_member_of_domain)
    {
        $this->container['is_user_member_of_domain'] = $is_user_member_of_domain;

        return $this;
    }

    /**
     * Gets referenced_user_is_member_of_domain
     *
     * @return ?bool
     */
    public function getReferencedUserIsMemberOfDomain()
    {
        return $this->container['referenced_user_is_member_of_domain'];
    }

    /**
     * Sets referenced_user_is_member_of_domain
     *
     * @param ?bool $referenced_user_is_member_of_domain referenced_user_is_member_of_domain
     *
     * @return $this
     */
    public function setReferencedUserIsMemberOfDomain($referenced_user_is_member_of_domain)
    {
        $this->container['referenced_user_is_member_of_domain'] = $referenced_user_is_member_of_domain;

        return $this;
    }

    /**
     * Gets referenced_user_id
     *
     * @return ?string
     */
    public function getReferencedUserId()
    {
        return $this->container['referenced_user_id'];
    }

    /**
     * Sets referenced_user_id
     *
     * @param ?string $referenced_user_id referenced_user_id
     *
     * @return $this
     */
    public function setReferencedUserId($referenced_user_id)
    {
        $this->container['referenced_user_id'] = $referenced_user_id;

        return $this;
    }

    /**
     * Gets proxy_status
     *
     * @return ?string
     */
    public function getProxyStatus()
    {
        return $this->container['proxy_status'];
    }

    /**
     * Sets proxy_status
     *
     * @param ?string $proxy_status proxy_status
     *
     * @return $this
     */
    public function setProxyStatus($proxy_status)
    {
        $this->container['proxy_status'] = $proxy_status;

        return $this;
    }

    /**
     * Gets proxy_type
     *
     * @return ?string
     */
    public function getProxyType()
    {
        return $this->container['proxy_type'];
    }

    /**
     * Sets proxy_type
     *
     * @param ?string $proxy_type proxy_type
     *
     * @return $this
     */
    public function setProxyType($proxy_type)
    {
        $this->container['proxy_type'] = $proxy_type;

        return $this;
    }

    /**
     * Gets proxy_level
     *
     * @return ?string
     */
    public function getProxyLevel()
    {
        return $this->container['proxy_level'];
    }

    /**
     * Sets proxy_level
     *
     * @param ?string $proxy_level proxy_level
     *
     * @return $this
     */
    public function setProxyLevel($proxy_level)
    {
        $this->container['proxy_level'] = $proxy_level;

        return $this;
    }

    /**
     * Gets latitude
     *
     * @return double
     */
    public function getLatitude()
    {
        return $this->container['latitude'];
    }

    /**
     * Sets latitude
     *
     * @param double $latitude latitude
     *
     * @return $this
     */
    public function setLatitude($latitude)
    {
        $this->container['latitude'] = $latitude;

        return $this;
    }

    /**
     * Gets longitude
     *
     * @return double
     */
    public function getLongitude()
    {
        return $this->container['longitude'];
    }

    /**
     * Sets longitude
     *
     * @param double $longitude longitude
     *
     * @return $this
     */
    public function setLongitude($longitude)
    {
        $this->container['longitude'] = $longitude;

        return $this;
    }

    /**
     * Gets city
     *
     * @return ?string
     */
    public function getCity()
    {
        return $this->container['city'];
    }

    /**
     * Sets city
     *
     * @param ?string $city city
     *
     * @return $this
     */
    public function setCity($city)
    {
        $this->container['city'] = $city;

        return $this;
    }

    /**
     * Gets state
     *
     * @return ?string
     */
    public function getState()
    {
        return $this->container['state'];
    }

    /**
     * Sets state
     *
     * @param ?string $state state
     *
     * @return $this
     */
    public function setState($state)
    {
        $this->container['state'] = $state;

        return $this;
    }

    /**
     * Gets country
     *
     * @return ?string
     */
    public function getCountry()
    {
        return $this->container['country'];
    }

    /**
     * Sets country
     *
     * @param ?string $country country
     *
     * @return $this
     */
    public function setCountry($country)
    {
        $this->container['country'] = $country;

        return $this;
    }

    /**
     * Gets device
     *
     * @return ?string
     */
    public function getDevice()
    {
        return $this->container['device'];
    }

    /**
     * Sets device
     *
     * @param ?string $device device
     *
     * @return $this
     */
    public function setDevice($device)
    {
        $this->container['device'] = $device;

        return $this;
    }

    /**
     * Gets browser
     *
     * @return ?string
     */
    public function getBrowser()
    {
        return $this->container['browser'];
    }

    /**
     * Sets browser
     *
     * @param ?string $browser browser
     *
     * @return $this
     */
    public function setBrowser($browser)
    {
        $this->container['browser'] = $browser;

        return $this;
    }

    /**
     * Gets os
     *
     * @return ?string
     */
    public function getOs()
    {
        return $this->container['os'];
    }

    /**
     * Sets os
     *
     * @param ?string $os os
     *
     * @return $this
     */
    public function setOs($os)
    {
        $this->container['os'] = $os;

        return $this;
    }

    /**
     * Gets affected_user_id
     *
     * @return ?string
     */
    public function getAffectedUserId()
    {
        return $this->container['affected_user_id'];
    }

    /**
     * Sets affected_user_id
     *
     * @param ?string $affected_user_id affected_user_id
     *
     * @return $this
     */
    public function setAffectedUserId($affected_user_id)
    {
        $this->container['affected_user_id'] = $affected_user_id;

        return $this;
    }

    /**
     * Gets affected_user_is_member_of_domain
     *
     * @return ?bool
     */
    public function getAffectedUserIsMemberOfDomain()
    {
        return $this->container['affected_user_is_member_of_domain'];
    }

    /**
     * Sets affected_user_is_member_of_domain
     *
     * @param ?bool $affected_user_is_member_of_domain affected_user_is_member_of_domain
     *
     * @return $this
     */
    public function setAffectedUserIsMemberOfDomain($affected_user_is_member_of_domain)
    {
        $this->container['affected_user_is_member_of_domain'] = $affected_user_is_member_of_domain;

        return $this;
    }

    /**
     * Gets data
     *
     * @return map[string,object]
     */
    public function getData()
    {
        return $this->container['data'];
    }

    /**
     * Sets data
     *
     * @param map[string,object] $data data
     *
     * @return $this
     */
    public function setData($data)
    {
        $this->container['data'] = $data;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    #[\ReturnTypeWillChange]
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}

